name: Publish wiki

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/publish-wiki.yml"

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the main repository
      - name: Checkout the main repository
        uses: actions/checkout@v3

      # Step 2: Checkout the wiki repository
      - name: Checkout the wiki repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      # Step 3: Rebuild the Wiki
      - name: Rebuilding the Wiki
        run: |
          cd wiki
          git rm -rf .
          git clean -fd
          cd ..
          cp -r docs/. wiki/  
          if [ -f docs/_Sidebar.md ]; then  
            cp docs/_Sidebar.md wiki/  
          fi
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update Wiki and Sidebar" || echo "No changes to commit"
          git push
